ci: use ccache in ci/kokoro/install builds (#3894)
On pull-request builds, and if available, download the
ccache tarball and store them in `ci/kokoro/install/ccache-contents`.
The Dockerfile then extracts this tarball in `/h/.ccache` and configures
ccache to use that directory.

At the end of a successful build, and if the build is a
continuous integration build (the opposite of a pull-request build)
we update the tarball and upload it to the GCS folder.

diff --git a/ci/kokoro/install/Dockerfile.centos-7 b/ci/kokoro/install/Dockerfile.centos-7
--- a/ci/kokoro/install/Dockerfile.centos-7
+++ b/ci/kokoro/install/Dockerfile.centos-7
@@ -34,7 +34,7 @@ RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.
 RUN yum install -y centos-release-scl yum-utils
 RUN yum-config-manager --enable rhel-server-rhscl-7-rpms
 RUN yum makecache && \
-    yum install -y automake cmake3 curl-devel gcc gcc-c++ git libtool \
+    yum install -y automake ccache cmake3 curl-devel gcc gcc-c++ git libtool \
         make openssl-devel pkgconfig tar wget which zlib-devel
 RUN ln -sf /usr/bin/cmake3 /usr/bin/cmake && ln -sf /usr/bin/ctest3 /usr/bin/ctest
 # ```
@@ -174,6 +174,7 @@ RUN wget -q https://github.com/googleapis/google-cloud-cpp-common/archive/v0.25.
 
 FROM devtools AS install
 ARG NCPU=4
+ARG DISTRO="distro-name"
 
 # #### Compile and install the main project
 
@@ -182,6 +183,19 @@ ARG NCPU=4
 # ```bash
 WORKDIR /home/build/project
 COPY . /home/build/project
+## [START IGNORED]
+# This is just here to speed up the pre-submit builds and should not be part
+# of the instructions on how to compile the code.
+ENV CCACHE_DIR=/h/.ccache
+RUN mkdir -p /h/.ccache; \
+    echo "max_size = 4.0G" >"/h/.ccache/ccache.conf"; \
+    if [ -r "ci/kokoro/install/ccache-contents/${DISTRO}.tar.gz" ]; then \
+      tar -xf "ci/kokoro/install/ccache-contents/${DISTRO}.tar.gz" -C /h; \
+      ccache --show-stats; \
+      ccache --zero-stats; \
+    fi; \
+    true # Ignore all errors, failures in caching should not break the build
+## [END IGNORED]
 RUN cmake -H. -Bcmake-out
 RUN cmake --build cmake-out -- -j "${NCPU:-4}"
 WORKDIR /home/build/project/cmake-out
@@ -206,8 +220,12 @@ WORKDIR /home/build/quickstart-cmake/bigtable
 COPY google/cloud/bigtable/quickstart /home/build/quickstart-cmake/bigtable
 RUN env -u PKG_CONFIG_PATH cmake -H. -B/i/bigtable
 RUN cmake --build /i/bigtable
-
 WORKDIR /home/build/quickstart-cmake/storage
 COPY google/cloud/storage/quickstart /home/build/quickstart-cmake/storage
 RUN env -u PKG_CONFIG_PATH cmake -H. -B/i/storage
 RUN cmake --build /i/storage
+
+
+# This is just here to speed up the pre-submit builds and should not be part
+# of the instructions on how to compile the code.
+RUN ccache --show-stats --zero-stats || true
diff --git a/ci/kokoro/install/Dockerfile.fedora b/ci/kokoro/install/Dockerfile.fedora
--- a/ci/kokoro/install/Dockerfile.fedora
+++ b/ci/kokoro/install/Dockerfile.fedora
@@ -28,7 +28,7 @@ ARG NCPU=4
 
 # ```bash
 RUN dnf makecache && \
-    dnf install -y cmake gcc-c++ git make openssl-devel pkgconfig \
+    dnf install -y ccache cmake gcc-c++ git make openssl-devel pkgconfig \
         zlib-devel
 # ```
 
@@ -122,6 +122,7 @@ RUN wget -q https://github.com/googleapis/google-cloud-cpp-common/archive/v0.25.
 
 FROM devtools AS install
 ARG NCPU=4
+ARG DISTRO="distro-name"
 
 # #### Compile and install the main project
 
@@ -130,6 +131,19 @@ ARG NCPU=4
 # ```bash
 WORKDIR /home/build/project
 COPY . /home/build/project
+## [START IGNORED]
+# This is just here to speed up the pre-submit builds and should not be part
+# of the instructions on how to compile the code.
+ENV CCACHE_DIR=/h/.ccache
+RUN mkdir -p /h/.ccache; \
+    echo "max_size = 4.0G" >"/h/.ccache/ccache.conf"; \
+    if [ -r "ci/kokoro/install/ccache-contents/${DISTRO}.tar.gz" ]; then \
+      tar -xf "ci/kokoro/install/ccache-contents/${DISTRO}.tar.gz" -C /h; \
+      ccache --show-stats; \
+      ccache --zero-stats; \
+    fi; \
+    true # Ignore all errors, failures in caching should not break the build
+## [END IGNORED]
 RUN cmake -H. -Bcmake-out
 RUN cmake --build cmake-out -- -j "${NCPU:-4}"
 WORKDIR /home/build/project/cmake-out
@@ -154,8 +168,12 @@ WORKDIR /home/build/quickstart-cmake/bigtable
 COPY google/cloud/bigtable/quickstart /home/build/quickstart-cmake/bigtable
 RUN env -u PKG_CONFIG_PATH cmake -H. -B/i/bigtable
 RUN cmake --build /i/bigtable
-
 WORKDIR /home/build/quickstart-cmake/storage
 COPY google/cloud/storage/quickstart /home/build/quickstart-cmake/storage
 RUN env -u PKG_CONFIG_PATH cmake -H. -B/i/storage
 RUN cmake --build /i/storage
+
+
+# This is just here to speed up the pre-submit builds and should not be part
+# of the instructions on how to compile the code.
+RUN ccache --show-stats --zero-stats || true
